### ISSUE TITLE
Tip, het copyright symbool is een HTML special character

### ISSUE THREAD

**Issue by JeroenHeemskerk** [userieur/educom-webshop-basis#13]
https://github.com/userieur/educom-webshop-basis/blob/7608dbd4fa9c7e8877dc7668a1aacc31534a7c22/index.html#L22

Hier staat de unicode van het copyright symbool, maar dit is lastig leesbaar in de HTML, er is ook een special character die je kunt gebruiken.

**Comment by JeroenHeemskerk** [comment]
In deze regel staat ook wat javascript, met de `<script>` tag, dat was geen onderdeel van de eerste opdracht, maar is ook niet erg als je dat wel gebruikt.

**Comment by userieur** [comment]
Copyright aangepast, en script vond ik leuker omdat het dan voor altijd klopt, kon ook een versie maken dat het van 2022 tot nu is, om even te spelen.
