### ISSUE TITLE
Een klik op de labels voor email en telefoon zorgen dat de cursor in het last-name veld komt in plaats van het juiste veld

### ISSUE THREAD

**Issue by JeroenHeemskerk** [userieur/educom-webshop-basis#15]
https://github.com/userieur/educom-webshop-basis/blob/7608dbd4fa9c7e8877dc7668a1aacc31534a7c22/contact.html#L17-L21

Het `for` attribuut in de labels voor E-mail Adres en Telefoon wijzen naar het id van de input voor de achternaam, waarschijnlijk een copy-paste foutje..

**Comment by userieur** [comment]
Ik heb het aangepast, en meteen de type's ook, ik zag dat er wat meer combi's mogelijk waren. Komt met nieuwe push
