### ISSUE TITLE
Mis een text veld op je contact formulier om een bericht achter te laten

### ISSUE THREAD

**Issue by JeroenHeemskerk** [userieur/educom-webshop-basis#17]
https://github.com/userieur/educom-webshop-basis/blob/7608dbd4fa9c7e8877dc7668a1aacc31534a7c22/contact.html#L29-L31

Mis dit deel van de opdracht "Een invoerveld voor het bericht waarover ze contact willen opnemen (met meerdere regels).:"

**Comment by userieur** [comment]
Wederom oeps
