### ISSUE TITLE
Er staat een <form> tag binnen een <form>

### ISSUE THREAD

**Issue by JeroenHeemskerk** [userieur/educom-webshop-basis#18]
https://github.com/userieur/educom-webshop-basis/blob/7608dbd4fa9c7e8877dc7668a1aacc31534a7c22/contact.html#L24-L32

Er staat een extra `<form>` tag op regel 24 en 29 die er niet hoort.
Als je zaken bij elkaar wilt houden, kijk dan eens naar een `<fieldset>` met `<legend>` element

**Comment by userieur** [comment]
Ja het voelde al niet goed, heb nu fieldset
